language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate --settings=roulette.settings_marcus
  - python manage.py test --settings=roulette.settings_marcus