# Generated by Django 2.0 on 2017-12-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ('turn', 'order')},
        ),
    ]
